/*  setState():  function is special because whenever it is called entire application will be re-render...
	This means that if a child property is different from the last state, it will be re-rendered with the new value.
	This is where  Firebase and React agree on. it data changes just change the state so related fields will be refreshed easily....
*/